routes/web.php
<?php

use App\Http\Controllers\Backend\AdditionalController;
use App\Http\Controllers\Backend\ApplicationProposalController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\CountryController;
use App\Http\Controllers\Backend\OrderController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\SliderController;
use App\Http\Controllers\Backend\SubscribeController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\LangController;
use App\Http\Middleware\TranslateMiddleware;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();

// ------------------------------------------- BackEnd ------------------------------------------- \\
Route::group(['middleware'=> ['auth', 'admin'], 'prefix' => '/admin'], function() {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('/country', CountryController::class);
    Route::resource('/user', UserController::class);
    Route::resource('/slider', SliderController::class);
    Route::resource('/category', CategoryController::class);
    Route::resource('/product', ProductController::class);
    Route::get('/product/delete/image/{image}', [ProductController::class, 'deleteOneImage'])->name('product.delete.image');
    Route::resource('/order', OrderController::class);
    Route::post('/order/card/delete', [OrderController::class, 'deleteCardOrder'])->name('order.card.delete');
    Route::get('/order/finish/get', [OrderController::class, 'finished'])->name('order.finished');
    Route::post('/order/status/{order}', [OrderController::class, 'status'])->name('order.status');
    Route::resource('/application-proposal', ApplicationProposalController::class);

    Route::get('/subscribe', [SubscribeController::class, 'index'])->name('subscribe.index');
    Route::get('/subscribe/send/{id}', [SubscribeController::class, 'send'])->name('subscribe.send');
});
// ---------------------------------------- [END] BackEnd ---------------------------------------- \\




// ------------------------------------------- FrontEnd ------------------------------------------- \\

// change language
Route::get('setlocale/{lang}/', [LangController::class,'lang'])->name('setlocale');


//Route::group( ['prefix' => LangController::getLocaleSubmit(), 'namespace' => 'App\Http\Controllers\Frontend'], function() {
Route::group( ['namespace' => 'App\Http\Controllers\Frontend'], function() {
    Route::get('/', 'HomeController@home')->name('home.page');
    Route::get('/about', 'HomeController@about')->name('about');
    Route::get('/contact', 'HomeController@contact')->name('contact');
    Route::post('/contact/send', 'HomeController@applicationProposal')->name('contact.application.proposal');
    Route::get('/news', 'HomeController@news')->name('news');
    Route::get('/shop', 'HomeController@shop')->name('shop');
    Route::get('/singleNews', 'HomeController@singleNews')->name('single.news');
    Route::get('/singleProduct/{id}', 'HomeController@singleProduct')->name('single.product');
    Route::post('/search', 'HomeController@search')->name('search');
    Route::post('/subscribe', 'UserController@subscribe')->name('subscribe');



    Route::group(['prefix' => '/guest', 'middleware'=> ['guest']], function() {
        Route::get('/cart', 'GuestController@cart')->name('guest.cart');
        Route::get('/checkout', 'GuestController@checkout')->name('guest.checkout');
        Route::post('/order', 'GuestController@createOrder')->name('guest.order');
    });

    Route::group(['middleware'=> ['auth']], function() {
        Route::get('/home', 'UserController@profile')->name('home');
        Route::post('/change/settings', 'UserController@settings')->name('settings.user');
        Route::get('/cart', 'HomeController@cart')->name('cart');
        Route::get('/checkout', 'HomeController@checkout')->name('checkout');

        Route::group(['middleware'=> ['is_block']], function() {
            Route::group(['prefix' => '/order'], function () {
                Route::post('/', 'OrderController@create')->name('order');
                Route::post('/again', 'OrderController@createAgain')->name('order.again');
            });

            Route::group(['prefix' => '/card'], function () {
                Route::get('/add/{product}', 'ShoppingCardController@create')->name('shopping.card.create');
                Route::post('/update/{shopping}', 'ShoppingCardController@update')->name('shopping.card.update');
                Route::get('/delete/{shopping}', 'ShoppingCardController@delete')->name('shopping.card.delete');
            });
        });
    });

});

// ---------------------------------------- [END] FrontEnd ---------------------------------------- \\

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends LocalizedModel
{
    use HasFactory;

    protected $table = 'categories';

    protected $fillable = [
        'path'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function products()
    {
        return $this->hasMany(Product::class,'category_id','id');
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Hellper\HellperFile;
use App\Http\Controllers\Controller;
use App\Http\Requests\Category\CreateRequest;
use App\Http\Requests\Category\EditRequest;
use App\Models\Category;
use App\Services\CategoryService;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    /**
     * @var CategoryService
     */
    protected CategoryService $category;

    /**
     * @param CategoryService $category
     */
    public function __construct(CategoryService $category)
    {
        $this->category = $category;
    }


    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $categories = Category::all();
        return view('backend.dashboard.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('backend.dashboard.category.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CreateRequest $request)
    {
        $data = $this->category->CreateOrUpdate($request->all());
        return redirect()->route('category.index')->with(['message' => $data['message']]);
    }

    /**
     * Display the specified resource.
     */
    public function show(Category $slider)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Category $category)
    {
        return view('backend.dashboard.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(EditRequest $request, Category $category)
    {
        $data = $this->category->CreateOrUpdate($request->all(), $category);
        return redirect()->route('category.index')->with(['message' => $data['message']]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Category $category)
    {
        HellperFile::deleteImage($category->path);
        $category->localizations()->delete();
        $category->delete();
        return redirect()->route('category.index')->with(['message' => 'Successfully Data deleted!']);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Hellper\HellperNotifyMessage;
use App\Http\Controllers\Controller;
use Vonage\Client;
use Vonage\SMS\Message\SMS;

class DashboardController extends Controller
{
    public function index()
    {
        return view('backend.dashboard.dashboard');
    }
}

resources/views/backend/dashboard/category/create.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Create</title>
@endsection

@section('css')

@endsection



@section('dashboard')
    <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            {{--                        <h1>Create</h1>--}}
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                                <li class="breadcrumb-item"><a href="{{route('category.index')}}">Category</a></li>
                                <li class="breadcrumb-item active">Create</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">Create</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->
                                <form role="form" action="{{route('category.store')}}" method="POST" enctype="multipart/form-data">
                                    @csrf

                                    @include("backend.components.translate")
                                    <div class="card-body">
                                        <div class="tab-content" id="custom-tabs-two-tabContent">
                                            @foreach($countriesGLOBAL as $key => $item)
                                                <div class="tab-pane fade  @if($key == 0) show active @endif" id="{{$item->lang}}" role="tabpanel" aria-labelledby="custom-tabs-two-{{$item->lang}}-tab">
                                                    <div class="card-body row">
                                                        <div class="form-group col-3">
                                                            <label for="exampleInputPassword1">Title {{$item->lang}}</label>
                                                            <input type="text" class="form-control" name="langs[{{ $item->lang }}][title]" id="exampleInputPassword1" placeholder="Title" value="{{ old('langs['.$item->lang.'][title]') }}"  >
                                                        </div>
                                                    </div>
                                                </div>
                                            @endforeach
                                        </div>
                                    </div>

                                    <hr>
                                    <div class="card-body row">
                                        <div class="form-group col-12">
                                            <label for="exampleInputFile">First Images</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file"  class="custom-file-input" name="image" id="imgfilesOne">
                                                    <label class="custom-file-label" for="imgfilesOne">Choose file</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="img-view-one">

                                        </div>
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary story-submit">Save</button>
                                    </div>
                                </form>
                            </div>
                            <!-- /.card -->
                        </div>
                        <!--/.col (left) -->
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
@endsection

@section('js')

@endsection

resources/views/backend/dashboard/category/edit.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Edit</title>
@endsection

@section('css')
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
@endsection

@section('dashboard')
    <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            {{--                        <h1>Create</h1>--}}
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                                <li class="breadcrumb-item"><a href="{{route('category.index')}}">Slider</a></li>
                                <li class="breadcrumb-item active">Edit</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">Edit</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->
                                <form role="form" action="{{route('category.update', $category->id)}}" method="POST" enctype="multipart/form-data">
                                    @method('PUT')
                                    @csrf
                                    @include("backend.components.translate")
                                    <div class="card-body">
                                        <div class="tab-content" id="custom-tabs-two-tabContent">
                                            @foreach($countriesGLOBAL as $key => $item)
                                                <div class="tab-pane fade  @if($key == 0) show active @endif" id="{{$item->lang}}" role="tabpanel" aria-labelledby="custom-tabs-two-{{$item->lang}}-tab">
                                                    <div class="card-body row">
                                                        <div class="form-group col-3">
                                                            <label for="exampleInputPassword1">Title</label>
                                                            <input type="text" class="form-control" name="langs[{{ $item->lang }}][title]" id="exampleInputPassword1" placeholder="Name" value="{{isset($category->localizations[$key]->title) ? $category->localizations[$key]->title : ''}}">
                                                        </div>
                                                    </div>
                                                </div>
                                            @endforeach
                                        </div>
                                    </div>

                                    <div class="card-body row">
                                        <div class="form-group col-12">
                                            <label for="exampleInputFile">First Images</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file"  class="custom-file-input" name="image" id="imgfilesOne">
                                                    <label class="custom-file-label" for="imgfilesOne">Choose file</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="img-view-one">

                                        </div>
                                        <img style="width: 50%" src="{{asset($category->path)}}" alt="">
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary story-submit">Save</button>
                                    </div>
                                </form>
                            </div>
                            <!-- /.card -->
                        </div>
                        <!--/.col (left) -->
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
@endsection

@section('js')

@endsection

resources/views/backend/dashboard/category/index.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Category</title>
@endsection

@section('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.4/css/buttons.dataTables.min.css">
@endsection



@section('dashboard')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Country</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                            <li class="breadcrumb-item active">Category</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div>
                                <a href="{{route('category.create')}}" class="btn btn-success" style="float: right; margin: 15px">Create</a>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>Title</th>
                                        <th>Access</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($categories as $key => $item)
                                        <tr>
                                            <td style="width: 15%"><img src="{{asset($item->path)}}" alt="" style="width: 50%"></td>
                                            <td>{{ \App\Hellper\GetLocalizedValue::GetValue($item, 'title') }}</td>
                                            <td>
                                                <div class="d-flex">
                                                    <a style="padding: 0px 5px;margin: 0px 8px;" href="{{ route("category.edit", $item->id) }}" class="btn btn-primary edit-access"><i  class="fas fa-edit" ></i></a>
                                                    <form method="POST" action="{{ route("category.destroy" , $item->id) }}">
                                                        @csrf
                                                        @method('DELETE')
                                                        <a href="javascript:;" onclick="return confirm('Are you sure you want to delete this item?');">
                                                            <button type="submit" style="padding: 0px 5px;" class="ml-2 btn btn-danger" >
                                                                <i class="fa fa-trash"></i>
                                                            </button>
                                                        </a>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('js')


@endsection