routes/web.php
<?php

use App\Http\Controllers\Backend\AdditionalController;
use App\Http\Controllers\Backend\ApplicationProposalController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\CountryController;
use App\Http\Controllers\Backend\OrderController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\SliderController;
use App\Http\Controllers\Backend\SubscribeController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\LangController;
use App\Http\Middleware\TranslateMiddleware;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();

// ------------------------------------------- BackEnd ------------------------------------------- \\
Route::group(['middleware'=> ['auth', 'admin'], 'prefix' => '/admin'], function() {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('/country', CountryController::class);
    Route::resource('/user', UserController::class);
    Route::resource('/slider', SliderController::class);
    Route::resource('/category', CategoryController::class);
    Route::resource('/product', ProductController::class);
    Route::get('/product/delete/image/{image}', [ProductController::class, 'deleteOneImage'])->name('product.delete.image');
    Route::resource('/order', OrderController::class);
    Route::post('/order/card/delete', [OrderController::class, 'deleteCardOrder'])->name('order.card.delete');
    Route::get('/order/finish/get', [OrderController::class, 'finished'])->name('order.finished');
    Route::post('/order/status/{order}', [OrderController::class, 'status'])->name('order.status');
    Route::resource('/application-proposal', ApplicationProposalController::class);

    Route::get('/subscribe', [SubscribeController::class, 'index'])->name('subscribe.index');
    Route::get('/subscribe/send/{id}', [SubscribeController::class, 'send'])->name('subscribe.send');
});
// ---------------------------------------- [END] BackEnd ---------------------------------------- \\




// ------------------------------------------- FrontEnd ------------------------------------------- \\

// change language
Route::get('setlocale/{lang}/', [LangController::class,'lang'])->name('setlocale');


//Route::group( ['prefix' => LangController::getLocaleSubmit(), 'namespace' => 'App\Http\Controllers\Frontend'], function() {
Route::group( ['namespace' => 'App\Http\Controllers\Frontend'], function() {
    Route::get('/', 'HomeController@home')->name('home.page');
    Route::get('/about', 'HomeController@about')->name('about');
    Route::get('/contact', 'HomeController@contact')->name('contact');
    Route::post('/contact/send', 'HomeController@applicationProposal')->name('contact.application.proposal');
    Route::get('/news', 'HomeController@news')->name('news');
    Route::get('/shop', 'HomeController@shop')->name('shop');
    Route::get('/singleNews', 'HomeController@singleNews')->name('single.news');
    Route::get('/singleProduct/{id}', 'HomeController@singleProduct')->name('single.product');
    Route::post('/search', 'HomeController@search')->name('search');
    Route::post('/subscribe', 'UserController@subscribe')->name('subscribe');



    Route::group(['prefix' => '/guest', 'middleware'=> ['guest']], function() {
        Route::get('/cart', 'GuestController@cart')->name('guest.cart');
        Route::get('/checkout', 'GuestController@checkout')->name('guest.checkout');
        Route::post('/order', 'GuestController@createOrder')->name('guest.order');
    });

    Route::group(['middleware'=> ['auth']], function() {
        Route::get('/home', 'UserController@profile')->name('home');
        Route::post('/change/settings', 'UserController@settings')->name('settings.user');
        Route::get('/cart', 'HomeController@cart')->name('cart');
        Route::get('/checkout', 'HomeController@checkout')->name('checkout');

        Route::group(['middleware'=> ['is_block']], function() {
            Route::group(['prefix' => '/order'], function () {
                Route::post('/', 'OrderController@create')->name('order');
                Route::post('/again', 'OrderController@createAgain')->name('order.again');
            });

            Route::group(['prefix' => '/card'], function () {
                Route::get('/add/{product}', 'ShoppingCardController@create')->name('shopping.card.create');
                Route::post('/update/{shopping}', 'ShoppingCardController@update')->name('shopping.card.update');
                Route::get('/delete/{shopping}', 'ShoppingCardController@delete')->name('shopping.card.delete');
            });
        });
    });

});

// ---------------------------------------- [END] FrontEnd ---------------------------------------- \\

app/Models/Country.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Country extends LocalizedModel
{
    use HasFactory;

    protected $table = 'countries';

    protected $fillable = [
        'lang',
        'path',
    ];
}

app/Http/Controllers/Backend/CountryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Hellper\HellperFile;
use App\Http\Controllers\Controller;
use App\Http\Requests\Country\CreateRequest;
use App\Http\Requests\Country\EditRequest;
use App\Models\Country;
use App\Services\CountryService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use function Symfony\Component\Mime\Header\all;

class CountryController extends Controller
{

    /**
     * @var CountryService
     */
    protected CountryService $country;

    /**
     * @param CountryService $country
     */
    public function __construct(CountryService $country)
    {
        $this->country = $country;
    }


    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $countries = Country::all();
        return view('backend.dashboard.country.index', compact('countries'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('backend.dashboard.country.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CreateRequest $request)
    {
        $data = $this->country->CreateOrUpdate($request->all());
        return redirect()->route('country.index')->with(['message' => $data['message']]);
    }

    /**
     * Display the specified resource.
     */
    public function show(Country $country)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Country $country)
    {
        return view('backend.dashboard.country.edit', compact('country'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(EditRequest $request, Country $country)
    {
        $data = $this->country->CreateOrUpdate($request->all(), $country);
        return redirect()->route('country.index')->with(['message' => $data['message']]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Country $country)
    {
        HellperFile::deleteImage($country->path);
        $country->localizations()->delete();
        $country->delete();
        return redirect()->route('country.index')->with(['message' => 'Successfully Data deleted!']);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Hellper\HellperNotifyMessage;
use App\Http\Controllers\Controller;
use Vonage\Client;
use Vonage\SMS\Message\SMS;

class DashboardController extends Controller
{
    public function index()
    {
        return view('backend.dashboard.dashboard');
    }
}

resources/views/backend/dashboard/country/create.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Create</title>
@endsection

@section('css')

@endsection



@section('dashboard')
    <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            {{--                        <h1>Create</h1>--}}
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                                <li class="breadcrumb-item"><a href="{{route('country.index')}}">Header</a></li>
                                <li class="breadcrumb-item active">Create</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">Create</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->
                                <form role="form" action="{{route('country.store')}}" method="POST" enctype="multipart/form-data">
                                    @csrf

                                    @include("backend.components.translate")
                                    <div class="card-body">
                                        <div class="tab-content" id="custom-tabs-two-tabContent">
                                            @foreach($countriesGLOBAL as $key => $item)
                                                <div class="tab-pane fade  @if($key == 0) show active @endif" id="{{$item->lang}}" role="tabpanel" aria-labelledby="custom-tabs-two-{{$item->lang}}-tab">
                                                    <div class="card-body row">
                                                        <div class="form-group col-3">
                                                            <label for="exampleInputPassword1">Name {{$item->lang}}</label>
                                                            <input type="text" class="form-control" name="langs[{{ $item->lang }}][name]" id="exampleInputPassword1" placeholder="Title" value="{{ old('langs['.$item->lang.'][Name]') }}"  >
                                                        </div>
                                                    </div>
                                                </div>
                                            @endforeach
                                        </div>
                                    </div>

                                    <hr>
                                    <div class="card-body row">
                                        <div class="form-group col-6">
                                            <label for="exampleInputPassword2">Name</label>
                                            <input type="text" class="form-control" name="name" placeholder="Name" value="{{ old('name') }}"  >
                                        </div>
                                        <div class="form-group col-6">
                                            <label for="exampleInputPassword2">Lang</label>
                                            <input type="text" class="form-control" name="lang" placeholder="Lang" value="{{ old('lang') }}"  >
                                        </div>
                                        <div class="form-group col-12">
                                            <label for="exampleInputFile">First Images</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file"  class="custom-file-input" name="image" id="imgfilesOne">
                                                    <label class="custom-file-label" for="imgfilesOne">Choose file</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="img-view-one">

                                        </div>
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary story-submit">Save</button>
                                    </div>
                                </form>
                            </div>
                            <!-- /.card -->
                        </div>
                        <!--/.col (left) -->
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
@endsection

@section('js')

@endsection

resources/views/backend/dashboard/country/edit.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Edit</title>
@endsection

@section('css')
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
@endsection

@section('dashboard')
    <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            {{--                        <h1>Create</h1>--}}
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                                <li class="breadcrumb-item"><a href="{{route('country.index')}}">County</a></li>
                                <li class="breadcrumb-item active">Edit</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">Edit</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->
                                <form role="form" action="{{route('country.update', $country->id)}}" method="POST" enctype="multipart/form-data">
                                    @method('PUT')
                                    @csrf
                                    @include("backend.components.translate")
                                    <div class="card-body">
                                        <div class="tab-content" id="custom-tabs-two-tabContent">
                                            @foreach($countriesGLOBAL as $key => $item)
                                                <div class="tab-pane fade  @if($key == 0) show active @endif" id="{{$item->lang}}" role="tabpanel" aria-labelledby="custom-tabs-two-{{$item->lang}}-tab">
                                                    <div class="card-body row">
                                                        <div class="form-group col-3">
                                                            <label for="exampleInputPassword1">Title</label>
                                                            <input type="text" class="form-control" name="langs[{{ $item->lang }}][name]" id="exampleInputPassword1" placeholder="Name" value="{{isset($country->localizations[$key]->name) ? $country->localizations[$key]->name : ''}}">
                                                        </div>
                                                    </div>
                                                </div>
                                            @endforeach
                                        </div>
                                    </div>

                                    <div class="card-body row">
                                        <div class="form-group col-3">
                                            <label for="exampleInputPassword1">Lang</label>
                                            <input type="text" class="form-control" name="lang" id="exampleInputPassword1" placeholder="Lang" value="{{isset($country->lang) ? $country->lang : ''}}">
                                        </div>
                                        <div class="form-group col-12">
                                            <label for="exampleInputFile">First Images</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file"  class="custom-file-input" name="image" id="imgfilesOne">
                                                    <label class="custom-file-label" for="imgfilesOne">Choose file</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="img-view-one">

                                        </div>
                                        <img style="width: 50%" src="{{asset($country->path)}}" alt="">
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary story-submit">Save</button>
                                    </div>
                                </form>
                            </div>
                            <!-- /.card -->
                        </div>
                        <!--/.col (left) -->
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
@endsection

@section('js')

@endsection

resources/views/backend/dashboard/country/index.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Company</title>
@endsection

@section('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.4/css/buttons.dataTables.min.css">
@endsection



@section('dashboard')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Country</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                            <li class="breadcrumb-item active">Country</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div>
                                <a href="{{route('country.create')}}" class="btn btn-success" style="float: right; margin: 15px">Create</a>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>Name</th>
                                        <th>Lang</th>
                                        <th>Access</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($countries as $key => $item)
                                        <tr>
                                            <td style="width: 15%"><img src="{{asset($item->path)}}" alt="" style="width: 50%"></td>
                                            <td>{{ \App\Hellper\GetLocalizedValue::GetValue($item, 'name') }}</td>
                                            <td>{{ $item->lang }}</td>
                                            <td>
                                                <div class="d-flex">
                                                        <a style="padding: 0px 5px;margin: 0px 8px;" href="{{ route("country.edit", $item->id) }}" class="btn btn-primary edit-access"><i  class="fas fa-edit" ></i></a>
                                                    @if($countries->count() > 2 )
                                                        <form method="POST" action="{{ route("country.destroy" , $item->id) }}">
                                                            @csrf
                                                            @method('DELETE')
                                                            <a href="javascript:;" onclick="return confirm('Are you sure you want to delete this item?');">
                                                                <button type="submit" style="padding: 0px 5px;" class="ml-2 btn btn-danger" >
                                                                    <i class="fa fa-trash"></i>
                                                                </button>
                                                            </a>
                                                        </form>
                                                    @endif
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('js')


@endsection