routes/web.php
<?php

use App\Http\Controllers\Backend\AdditionalController;
use App\Http\Controllers\Backend\ApplicationProposalController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\CountryController;
use App\Http\Controllers\Backend\OrderController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\SliderController;
use App\Http\Controllers\Backend\SubscribeController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\LangController;
use App\Http\Middleware\TranslateMiddleware;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();

// ------------------------------------------- BackEnd ------------------------------------------- \\
Route::group(['middleware'=> ['auth', 'admin'], 'prefix' => '/admin'], function() {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('/country', CountryController::class);
    Route::resource('/user', UserController::class);
    Route::resource('/slider', SliderController::class);
    Route::resource('/category', CategoryController::class);
    Route::resource('/product', ProductController::class);
    Route::get('/product/delete/image/{image}', [ProductController::class, 'deleteOneImage'])->name('product.delete.image');
    Route::resource('/order', OrderController::class);
    Route::post('/order/card/delete', [OrderController::class, 'deleteCardOrder'])->name('order.card.delete');
    Route::get('/order/finish/get', [OrderController::class, 'finished'])->name('order.finished');
    Route::post('/order/status/{order}', [OrderController::class, 'status'])->name('order.status');
    Route::resource('/application-proposal', ApplicationProposalController::class);

    Route::get('/subscribe', [SubscribeController::class, 'index'])->name('subscribe.index');
    Route::get('/subscribe/send/{id}', [SubscribeController::class, 'send'])->name('subscribe.send');
});
// ---------------------------------------- [END] BackEnd ---------------------------------------- \\




// ------------------------------------------- FrontEnd ------------------------------------------- \\

// change language
Route::get('setlocale/{lang}/', [LangController::class,'lang'])->name('setlocale');


//Route::group( ['prefix' => LangController::getLocaleSubmit(), 'namespace' => 'App\Http\Controllers\Frontend'], function() {
Route::group( ['namespace' => 'App\Http\Controllers\Frontend'], function() {
    Route::get('/', 'HomeController@home')->name('home.page');
    Route::get('/about', 'HomeController@about')->name('about');
    Route::get('/contact', 'HomeController@contact')->name('contact');
    Route::post('/contact/send', 'HomeController@applicationProposal')->name('contact.application.proposal');
    Route::get('/news', 'HomeController@news')->name('news');
    Route::get('/shop', 'HomeController@shop')->name('shop');
    Route::get('/singleNews', 'HomeController@singleNews')->name('single.news');
    Route::get('/singleProduct/{id}', 'HomeController@singleProduct')->name('single.product');
    Route::post('/search', 'HomeController@search')->name('search');
    Route::post('/subscribe', 'UserController@subscribe')->name('subscribe');



    Route::group(['prefix' => '/guest', 'middleware'=> ['guest']], function() {
        Route::get('/cart', 'GuestController@cart')->name('guest.cart');
        Route::get('/checkout', 'GuestController@checkout')->name('guest.checkout');
        Route::post('/order', 'GuestController@createOrder')->name('guest.order');
    });

    Route::group(['middleware'=> ['auth']], function() {
        Route::get('/home', 'UserController@profile')->name('home');
        Route::post('/change/settings', 'UserController@settings')->name('settings.user');
        Route::get('/cart', 'HomeController@cart')->name('cart');
        Route::get('/checkout', 'HomeController@checkout')->name('checkout');

        Route::group(['middleware'=> ['is_block']], function() {
            Route::group(['prefix' => '/order'], function () {
                Route::post('/', 'OrderController@create')->name('order');
                Route::post('/again', 'OrderController@createAgain')->name('order.again');
            });

            Route::group(['prefix' => '/card'], function () {
                Route::get('/add/{product}', 'ShoppingCardController@create')->name('shopping.card.create');
                Route::post('/update/{shopping}', 'ShoppingCardController@update')->name('shopping.card.update');
                Route::get('/delete/{shopping}', 'ShoppingCardController@delete')->name('shopping.card.delete');
            });
        });
    });

});

// ---------------------------------------- [END] FrontEnd ---------------------------------------- \\

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'type',
        'email',
        'password',
        'block',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function shoppingCard()
    {
        return $this->hasMany(ShoppingCard::class,'user_id','id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function information()
    {
        return $this->hasOne(UserInformation::class,'user_id','id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function order()
    {
        return $this->hasMany(Order::class,'user_id','id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function applicationProposal()
    {
        return $this->hasMany(ApplicationProposal::class,'user_id','id');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Hellper\HellperNotifyMessage;
use App\Http\Controllers\Controller;
use Vonage\Client;
use Vonage\SMS\Message\SMS;

class DashboardController extends Controller
{
    public function index()
    {
        return view('backend.dashboard.dashboard');
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Hellper\HellperNotifyMessage;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Services\UserService;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * @var UserService
     */
    protected UserService $user;

    /**
     * @param UserService $user
     */
    public function __construct(UserService $user)
    {
        $this->user = $user;
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Foundation\Application
     */
    public function index()
    {
        $users = User::whereNot('type', 'admin')->orderBy('id', 'DESC')->paginate(10);
        return view('backend.dashboard.user.index', compact('users'));
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Foundation\Application
     */
    public function create()
    {
        return view('backend.dashboard.user.create');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $data = $this->user->CreateOrUpdate($request->all());
        return redirect()->route('user.index')->with(['message' => $data['message']]);
    }

    /**
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function show(User $user)
    {
        $this->user->block($user);
        return redirect()->back();
    }

    /**
     * @param User $user
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Foundation\Application
     */
    public function edit(User $user)
    {
        return view('backend.dashboard.user.edit', compact('user'));
    }

    /**
     * @param Request $request
     * @param string $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, string $id)
    {
        $data = $this->user->CreateOrUpdate($request->all(), $id);
        return redirect()->route('user.index')->with(['message' => $data['message']]);
    }

    /**
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('user.index')->with(['message' => HellperNotifyMessage::messageNotify('delete')]);
    }
}

app/Http/Controllers/Frontend/UserController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Subscribe\SubscribeRequest;
use App\Http\Requests\Profile\SettingsRequest;
use App\Models\Order;
use App\Models\Subscribe;
use App\Models\User;
use App\Models\UserInformation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use function Symfony\Component\Routing\Loader\Configurator\collection;

class UserController extends Controller
{
    /**
     * @param SettingsRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function settings(SettingsRequest $request): \Illuminate\Http\RedirectResponse
    {
        $user = auth()->user();
        $user->name = $request->name;
        if (isset($request->password) && isset($request->old_password) && Hash::check($request->old_password, $user->password)){
            $user->password = Hash::make($request->password);
        }
        $user->save();

        UserInformation::query()->updateOrCreate(
            ['user_id'=>$user->id],
            [
                'user_id'=>$user->id,
                'phone' => $request->phone,
                'city' => $request->city,
                'address' => $request->address,
            ]
        );

        return redirect()->back();
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Foundation\Application
     */
    public function profile(): \Illuminate\Foundation\Application|\Illuminate\Contracts\View\View|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\Foundation\Application
    {
        $user = auth()->user();
        $authUser = $user->load(['order' =>function($query){
            $query->with(['card' => function($q){
                $q->with(['product' => function($y) {
                    $y->with('images');
                }]);
            }]); //->whereNot('status', 'finished')
        }]);

        $orderWaiting = $authUser->order;
        $ordersCount = $authUser->order->count();
        $orderHistory = $ordersCount ? $authUser->order->sortByDesc('id')->take(10) : [];

        return view('frontend.pages.profile', compact('orderWaiting','orderHistory', 'ordersCount'));
    }

    /**
     * @param SubscribeRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function subscribe(SubscribeRequest $request): \Illuminate\Http\RedirectResponse
    {
        Subscribe::query()->create([
            'email' => $request->email,
        ]);
        return redirect()->back()->with(['success' => __('global.success')]);
    }
}

resources/views/backend/dashboard/user/create.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Create</title>
@endsection

@section('css')

@endsection



@section('dashboard')
    <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>Create</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                                <li class="breadcrumb-item"><a href="{{route('user.index')}}">User</a></li>
                                <li class="breadcrumb-item active">Create</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">Create</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->
                                <form role="form" action="{{route('user.store')}}" method="POST">
                                    @csrf
                                    <div class="card-body row">
                                        <div class="form-group col-6">
                                            <label for="exampleInputPassword1">Name</label>
                                            <input type="text" class="form-control" name="name" placeholder="Name" value="{{ old('name') }}"  >
                                        </div>
                                        <div class="form-group col-6">
                                            <label for="exampleInputPassword2">Email</label>
                                            <input type="text" class="form-control" name="email" placeholder="Email" value="{{ old('email') }}"  >
                                        </div>
                                        <div class="form-group col-6">
                                            <label for="exampleInputPassword3">Password</label>
                                            <input type="text" class="form-control" name="password" placeholder="password" value="{{ old('password') }}"  >
                                        </div>
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary story-submit">Save</button>
                                    </div>
                                </form>
                            </div>
                            <!-- /.card -->
                        </div>
                        <!--/.col (left) -->
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
@endsection

@section('js')

@endsection

resources/views/backend/dashboard/user/edit.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Edit</title>
@endsection

@section('css')
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
@endsection

@section('dashboard')
    <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            {{--                        <h1>Create</h1>--}}
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                                <li class="breadcrumb-item"><a href="{{route('user.index')}}">User</a></li>
                                <li class="breadcrumb-item active">Edit</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">Edit</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->
                                <form role="form" action="{{route('user.update', $user->id)}}" method="POST">
                                    @method('PUT')
                                    @csrf
                                    <div class="card-body row">
                                        <div class="form-group col-6">
                                            <label for="exampleInputPassword1">Name</label>
                                            <input type="text" class="form-control" name="name" placeholder="Name" value="{{ $user->name }}"  >
                                        </div>
                                        <div class="form-group col-6">
                                            <label for="exampleInputPassword2">Email</label>
                                            <input type="text" class="form-control" name="email" placeholder="Email" value="{{ $user->email }}"  >
                                        </div>
                                        <div class="form-group col-6">
                                            <label for="exampleInputPassword3">Password</label>
                                            <input type="text" class="form-control" name="password" placeholder="password" value="{{ old('password') }}"  >
                                        </div>
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary story-submit">Save</button>
                                    </div>
                                </form>
                            </div>
                            <!-- /.card -->
                        </div>
                        <!--/.col (left) -->
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
@endsection

@section('js')

@endsection

resources/views/backend/dashboard/user/index.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Company</title>
@endsection

@section('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.4/css/buttons.dataTables.min.css">

    <style>
        .show-block-true {
            color: white;
            background: red;
            padding: 5px;
            border-radius: 5px;
            text-align: center;
            display: grid;
        }
        .show-unblock-false {
            color: black;
            background: rgba(128, 128, 128, 0.43);
            padding: 5px;
            border-radius: 5px;
            text-align: center;
            display: grid;
        }
    </style>
@endsection



@section('dashboard')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Users</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                            <li class="breadcrumb-item active">Users</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div>
                                <a href="{{route('user.create')}}" class="btn btn-success" style="float: right; margin: 15px">Create</a>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Type</th>
                                        <th>Block</th>
                                        <th>Access</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($users as $key => $item)
                                        <tr>
                                            <td>{{ $item->name }}</td>
                                            <td>{{ $item->email }}</td>
                                            <td>{{ $item->type }}</td>
                                            <td>
                                                @if(!$item->block)
                                                    <span class="show-unblock-false"> Unblocked </span>
                                                @else
                                                    <span class="show-block-true"> Blocked </span>
                                                @endif
                                            </td>
                                            <td>
                                                <div class="d-flex">
                                                    <a style="padding: 0px 5px;margin: 0px 8px;" href="{{ route("user.edit", $item->id) }}" class="btn btn-primary edit-access"><i  class="fas fa-edit" ></i></a>
                                                    @if(!$item->block)
                                                        <a style="padding: 0px 5px;margin: 0px 8px;" href="{{ route("user.show", $item->id) }}" class="btn btn-primary edit-access"><i  class="fa-solid fa-lock" ></i></a>
                                                    @else
                                                        <a style="padding: 0px 5px;margin: 0px 8px;" href="{{ route("user.show", $item->id) }}" class="btn btn-primary edit-access"><i  class="fa-solid fa-unlock" ></i></a>
                                                    @endif
                                                    <form method="POST" action="{{ route("user.destroy" , $item->id) }}">
                                                        @csrf
                                                        @method('DELETE')
                                                        <a href="javascript:;" onclick="return confirm('Are you sure you want to delete this item?');">
                                                            <button type="submit" style="padding: 0px 5px;" class="ml-2 btn btn-danger" >
                                                                <i class="fa fa-trash"></i>
                                                            </button>
                                                        </a>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach

                                    </tbody>
                                </table>
                            </div>
                            {{$users->appends(Request::except('page'))->links('pagination::bootstrap-4')}}
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('js')


@endsection